Test_form_URL = "https://bonigarcia.dev/selenium-webdriver-java/data-types.html" 
Calculator_URL = "https://bonigarcia.dev/selenium-webdriver-java/slow-calculator.html"
Shop_URL = "https://www.saucedemo.com/"
#Задание_1
first_name= "Иван"
last_name = "Петров"
address = "Ленина, 55-3"
email= "test@skypro.com"
phone = "+7985899998787"
zip_code = ""
city = "Москва"
country = "Россия"
job_position = "QA"
company ="SkyPro"